version: '3'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    environment:
      - PORT=$PORT
      - VERSION=$VERSION
      - LOG_LEVEL=$LOG_LEVEL
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/app
    command: npm start
